- name: Set Hostname
  ansible.builtin.shell: set-hostname backend

- name: Verify NodeJs
  ansible.builtin.shell: type npm
  register: npm
  ignore_errors: yes

- name: Install NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
  when: npm.rc != 0

- name: Copy Backend Service File
  ansible.builtin.template: 
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add Application User
  ansible.builtin.user:
    name: expense

- name: Include App Prerequisites 
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prerequisites
     
- name: Install NodeJs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter
    
- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql

- name: Load Schema
  ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'expense.backend.DB_HOST', region='us-east-1' ) }} -uroot -p{{ lookup('aws_ssm', 'expense.backend.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql
  become: yes

- name: Start Backend Service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes



        